# Generated by Django 3.2.6 on 2024-04-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
