# Generated by Django 3.2.6 on 2024-04-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answering', '0003_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen'),
        ),
    ]
