# Generated by Django 3.2.6 on 2024-04-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Answering', '0004_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
