# Generated by Django 3.2.6 on 2024-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Answering', '0005_remove_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=200, verbose_name=''),
        ),
    ]
