# Generated by Django 3.2.6 on 2024-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topics',
            field=models.TextField(verbose_name='Topics'),
        ),
    ]
