resources:
# Firewall rule
- name: app
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 0.0.0.0/0
    targetTags:
    - app
    allowed:
    - IPProtocol: TCP
      ports:
      - 8000

# Instance
- type: compute.v1.instance
  name: form-app
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/msbancoalpes/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-10
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/msbancoalpes/global/networks/default
      networkIP: 10.128.0.51
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - app